# Generated by Django 4.1.5 on 2024-03-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_delete_basemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_category',
        ),
    ]
