# Generated by Django 4.1.5 on 2024-05-01 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0008_remove_vehicle_vechile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vechile_category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='vechile_category', to='Car.carcompany'),
            preserve_default=False,
        ),
    ]
