# Generated by Django 4.1.5 on 2024-03-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_rename_booking_bookingcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcar',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
