# Generated by Django 4.1.5 on 2024-03-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_bookingcar_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcar',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
