# Generated by Django 4.1.5 on 2024-03-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_bookingcar_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcar',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
