# Generated by Django 4.1.5 on 2024-05-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='phone',
        ),
    ]
